"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000

format = """
$os\
$directory\
$git_branch\
$git_status\
$character"""

right_format = """
$package\
$rust\
$python\
$nodejs\
$ruby\
$golang\
$swift\
$dotnet\
$cmd_duration\
$time"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
staged = "+"
modified = "!"
renamed = "»"
deleted = "✘"

[package]
symbol = "󰏗 "
format = "is [$symbol](bold #F08428)[($version )](bold white)"

[rust]
symbol = " "
format = "via [$symbol](bold #DEA584)[($version )](bold white)"
detect_extensions = []
detect_files = ["Cargo.toml", ".rust-version"]

[python]
symbol = " "
format = "via [$symbol](bold #FFD43B)[(${version} )](bold white)"
detect_extensions = []
detect_files = ["requirements.txt", "pyproject.toml", "Pipfile", "setup.py", ".python-version", "tox.ini"]

[nodejs]
symbol = " "
format = "via [$symbol](bold #539E43)[($version )](bold white)"
detect_extensions = []
detect_files = [".node-version", ".nvmrc"]

[ruby]
symbol = " "
format = "via [$symbol](bold #CC342D)[($version )](bold white)"
detect_extensions = []
detect_files = ["Gemfile", ".ruby-version"]

[golang]
symbol = " "
format = "via [$symbol](bold #00ADD8)[($version )](bold white)"
detect_extensions = []
detect_files = ["go.mod", "go.sum", ".go-version"]

[swift]
symbol = "󰛥 "
format = "via [$symbol](bold #F05138)[($version )](bold white)"
detect_extensions = ["swift"]
detect_files = ["Package.swift"]

[dotnet]
symbol = " "
format = "via [$symbol](bold #512BD4)[($version )(🎯 $tfm )](bold white)"
detect_extensions = ["csproj", "fsproj", "xproj", "sln", "slnx"]

[cmd_duration]
min_time = 500
style = "bold yellow"
format = "took [$duration]($style)"

[username]
style_user = "bold red"
style_root = "bold red"
format = "[$user]($style) in "
show_always = false

[time]
disabled = false
time_format = "%I:%M %p"
style = "bold dim white"
format = " [󰥔 $time]($style)"
